// These records are stable preview content, not a claim of current government data.
// Official portals are included so users can verify the current rules before applying.
export const demoGovernmentSchemes = [
  {
    name: "Prime Minister's Employment Generation Programme (PMEGP)",
    description: "Illustrative preview of a credit-linked support route for eligible new micro-enterprises.",
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    category: "Self Employment",
    eligibility: ["Eligibility, project limits, and subsidy rules must be verified on the official portal."],
    benefits: ["Credit-linked margin money support may be available to eligible applicants."],
    documents: ["Identity, address, project, and bank documents may be requested."],
    applicationProcess: "Check the current process and eligibility on the official PMEGP portal.",
    officialUrl: "https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp",
    states: ["All India"],
    categoryTags: ["Self Employment", "MSME", "Rural Business"],
  },
  {
    name: "Pradhan Mantri Formalisation of Micro Food Processing Enterprises (PMFME)",
    description: "Illustrative preview of a formalisation and support route for eligible micro food-processing enterprises.",
    ministry: "Ministry of Food Processing Industries",
    category: "Food Processing",
    eligibility: ["Eligibility and support components vary; verify current guidelines on the official portal."],
    benefits: ["Eligible micro food-processing enterprises may receive support under the scheme guidelines."],
    documents: ["Identity, enterprise, bank, and project documents may be requested."],
    applicationProcess: "Review the current state and enterprise application guidance on the official portal.",
    officialUrl: "https://pmfme.mofpi.gov.in/",
    states: ["All India"],
    categoryTags: ["Food Processing", "MSME", "Dairy"],
  },
  {
    name: "Pradhan Mantri Mudra Yojana (PMMY)",
    description: "Illustrative preview of a small-business credit route offered through participating lenders.",
    ministry: "Department of Financial Services, Ministry of Finance",
    category: "MSME",
    eligibility: ["Lender assessment and current scheme rules apply; eligibility is not confirmed by this app."],
    benefits: ["Participating lenders may offer micro-enterprise loans under applicable categories."],
    documents: ["Identity, address, business, and lender-specific documents may be requested."],
    applicationProcess: "Verify the current product details with an official participating lender or portal.",
    officialUrl: "https://www.mudra.org.in/",
    states: ["All India"],
    categoryTags: ["MSME", "Retail", "Dairy", "Self Employment"],
  },
  {
    name: "Stand-Up India",
    description: "Illustrative preview of a bank-loan facilitation route for eligible women and SC/ST entrepreneurs.",
    ministry: "Department of Financial Services, Ministry of Finance",
    category: "Women Entrepreneurs",
    eligibility: ["Eligibility, borrower conditions, and loan terms must be checked on the official portal."],
    benefits: ["Eligible applicants may be facilitated for bank loans for a greenfield enterprise."],
    documents: ["Identity, category, business, project, and bank documents may be requested."],
    applicationProcess: "Use the official portal or participating bank for current application guidance.",
    officialUrl: "https://www.standupmitra.in/",
    states: ["All India"],
    categoryTags: ["Women Entrepreneurs", "MSME", "Self Employment"],
  },
];
